# Phundament nano

php:
  image: phundament/app:4.0.2
  command: sh src/run.sh
  environment:
    - DB_ENV_MYSQL_ROOT_USER=root
  links:
    - 'percona:DB'
  volumes:
    - /app

nginx:
  image: phundament/nginx-one:1.9
  links:
    - 'php:PHPFPM'
  ports:
    - 80
  volumes_from:
    - php

percona:
  image: percona:5.6
  environment:
    MYSQL_ROOT_PASSWORD: secretadmin
